### ISSUE TITLE
agencies with incorrect counties (or states)

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-cleaning#6]
related to https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/450

```
SELECT
    A.NAME,
    A.STATE_ISO,
    A.COUNTY_FIPS,
    A.airtable_uid,
    A.homepage_url,
    C.STATE_ISO COUNTIES_STATE_ISO
FROM
    AGENCIES A
    INNER JOIN COUNTIES C ON C.FIPS = A.COUNTY_FIPS
WHERE A.STATE_ISO != C.STATE_ISO
```
[incorrect counties or states.csv](https://github.com/user-attachments/files/17090273/incorrect.counties.or.states.csv)

Notes

- I exported airtable_uid and homepage_url for disambiguation + importing
  - I decided to use the `homepage_url` to find the "correct" state; however, many times the same `homepage_url` is incorrectly applied to multiple agencies, so it could be that the intended agency is now nonexistent in the database. This is not a huge deal because we don't have sources for these, and we know the homepages are not always correct.
  - this mistake also creates duplicate agencies
  - when the `agencies.state` is correct, typically the wrong county was assigned due to someone not being careful with state disambiguation for counties
  - when the `counties.state` is "correct", it's often that the homepage_url was wrong or a proper homepage was not found for the agency
- When there is no `homepage_url`, I defaulted to the agency's state
- Municipalities are usually wrong if the county is wrong
  - many municipalities are wrong, especially for county-level agencies—we should probably delete the municipalities for all counties which were deemed incorrect
- There's no rhyme or reason to which state is correct, or if it's a third state
- there are still plenty of agencies with incorrect homepages
- i un-approved some agencies which may still have mismatched county-states; I went back and cleared the counties (and munis) from those, but we should only build the locations table from approved agencies
- logic for the script to find appropriate counties:
  - add a column "correct_column" with options "county" "state" "neither", assigned based on whether the counties_state or agencies_state was correct (or neither)
  - if the `counties_state_iso` and `correct_state` match, change the `state_iso` to match, leaving the `county_fips`
  - if agencies_state or neither was correct, clear the `county_fips`
  - if "County" is in the `name`, truncate the string after "County" and use geocoding with that string + the state to find the correct `county_fips`
  - if not, search using the first word + correct state to find the correct `county_fips`

found `540` total

- added "correct_state" column to CSV, manually populated (usually evident from the URL)
- un-approved some agencies which do not seem to really exist
- un-approved some duplicate agencies
- fixed a handful of homepage URLs
- fixed some agencies which should be federal anyway

Recommendations

- if the state and county's state disagree, we should arbitrarily pick the county's as the "correct" one for the purposes of building the locations table
- we should have an agency checking script which:
   - tries to disambiguate duplicate homepages (if many agencies share a homepage, find the right one and clear the rest)
   - uses the state x locality combo to find a county
   - looks for homepages using disambiguated search terms (locality + state, county + state, all 3)

**Comment by josh-chamberlain** [comment]
these have the correct county_fips code. any agencies removed from the previous spreadsheet were resolved manually in Airtable, or un-approved for other reasons.

[updated_incorrect_counties_or_states.csv](https://github.com/user-attachments/files/17103808/updated_incorrect_counties_or_states.csv)

**Comment by josh-chamberlain** [comment]
@maxachis 485 agencies were updated in Airtable via CSV import, and the remainder manually...I _think_ I got them all! Let me know?

**Comment by maxachis** [comment]
@josh-chamberlain I spy 4-5 more (one might be addressed by the flighty Alaska County)

"Carlisle Police Department"	"18153"	"[""Sullivan""]"	"Carlisle"
"Ottawa County Sheriff's Office"	"45007"	"[""Anderson""]"	"West Olive"
"Whittier Police Department"	"02063"		"Whittier"
"Chinle Police District"	"04001"	"[""Apache""]"	"Chinle"
"Washington County Probation"	"42125"	"[""Washington""]"	"Washington"

**Comment by josh-chamberlain** [comment]
@maxachis OK, I fixed those!
